#!/bin/bash

set -e  # Exit immediately on error

echo "==== OnStart script: Installing custom packages ===="

PACKAGE_LIST=(
  "torch==2.6.0"
  "torchvision==0.21.0"
  "transformers==4.49.0"
  "torchdistill==1.1.2"
  "opensoundscape==0.11.0"
  "numpy==1.26.4" # Pipeline uncompatibile with Numpy >= 2.0.0
  "matplotlib==3.10.0"
  "scipy==1.15.2"
  "scikit-learn==1.6.1"
  "dask[dataframe]==2025.2.0"
  "librosa==0.10.2"
  "torchaudio==2.6.0"
)

echo "Installing packages..."
for PKG in "${PACKAGE_LIST[@]}"; do
    echo "Installing $PKG"
    pip3 install --no-cache-dir "$PKG"
    echo "Installed $PKG"
done

sudo apt-get install -y libgl1-mesa-dev

echo "==== Package installation complete ===="
