#!/bin/bash

set -e  # Exit immediately on error

echo "==== OnStart script: Installing custom packages ===="

PACKAGE_LIST=(
  "torch==2.6.0"
  "torchvision==0.21.0"
  "torchaudio==2.6.0"
  "transformers==4.49.0"
  "tflite==2.18.0"
  "opensoundscape==0.12.0"
  "numpy==1.26.4" # Pipeline uncompatibile with Numpy >= 2.0.0
  "transformers==4.49.0"
  "matplotlib==3.10.1"
  "scipy==1.15.2"
  "scikit-learn==1.6.1"
  "dask[dataframe]==2025.2.0"
  "librosa==0.11.0"
  "tensorflow[and-cuda]==2.17.1" # Exact Tensorflow required for Torch 2.6.0 compatibility because of joint dependencies
  "tensorflow-model-optimization==0.8.0"
)

echo "Installing packages..."
for PKG in "${PACKAGE_LIST[@]}"; do
    echo "Installing $PKG"
    pip3 install --no-cache-dir "$PKG"
    echo "Installed $PKG"
done

# Install Linux Libraries
sudo apt-get install -y libgl1-mesa-dev
sudo apt install xxd

echo "==== Package installation complete ===="
